### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by darosacezar** [alejoseb/Modbus-PI-Pico-FreeRTOS#2]
I am trying to compile your Modbus library as well as the example given, but I am getting the following error:
multiple definition of `mHandlers'; CMakeFiles/hello_world.dir/src/main.cpp.obj:C:\Users\user\Documents\Pico\Modbus-PI-Pico-FreeRTOS\MODBUS-LIB\Inc/Modbus.h:286: first defined here
collect2.exe: error: ld returned 1 exit status
Can you help me with it?

**Comment by alejoseb** [comment]
Hi, please pull the latest commit it should compile without issues now.
