### ISSUE TITLE
How to use a library

### ISSUE THREAD

**Issue by AlKoAl** [alejoseb/Modbus-PI-Pico-FreeRTOS#3]
Hello everyone!

This project may be dead, but I'll try anyway. Can you provide extended instructions on what to do? I downloaded everything according to the instructions but stopped at the change launch.json step. I deleted all the information from there and also change settings.json. After that I could started the building process and uf2 file was succesfully  been created. But i don't sure was I right doing such changings.

Do I understand correctly that main.cpp does the file turn into test_modbus?

**Comment by alejoseb** [comment]
This project is not dead. main.cpp contains a working example of the modbus library. You need an external USB to USART adapter to connect physically to the USART pins of the Raspberry Pi Pico and any client software on your PC. I added some links for the clients in the README file. If you were able to compile the project and flash the Pico then it should be working already.

**Comment by QwertyContender** [comment]
Can you explain how to properly setup the launch.json file? I am also using a UART to 485 board to avoid the need for a chip select (can I just comment out the lines?)
![image](https://user-images.githubusercontent.com/116194867/200947056-49ee031a-c2a5-494f-b072-53a214c6046e.png)
![image](https://user-images.githubusercontent.com/116194867/200947548-b7fedbe6-7139-432a-a84f-f45d0018f070.png)

**Comment by puneeth-kvsk** [comment]
Can you please help me modify the main.cpp code, so as to query a modbus slave energy meter with the following parameters:
1. Slave ID: 1
2. Baud Rate: 9600
3. Parity: none

Please find my altered code for main.cpp here:

[main_code.txt](https://github.com/alejoseb/Modbus-PI-Pico-FreeRTOS/files/10074019/main_code.txt)

Problem: CRC error received. Modbus request being sent to slave(led indication on energymeter slave). Reading modbus response register values failing
